name = "ScarletHeroesBot"
uuid = "b29c889e-4e21-11eb-1bfb-a15544c43cf1"
authors = ["Markus Amano <markus.a.amano@gmail.com>"]
version = "0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
